fix: improve reliability of screen view tracking
customerio/customerio-ios pull request #165
Opened 2022-06-07 15:06 UTC by levibostian

fixes: https://github.com/customerio/issues/issues/6616

QA test this PR from RH PR builds: https://github.com/customerio/RemoteHabits-iOS/pull/69

Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/blob/develop/docs/dev-notes/GIT-WORKFLOW.md). 
- [x] [Assign members of your team](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to review the pull request. 
- [x] Wait for pull request status checks to complete. If there are problems, fix them until you see that [all status checks are passing](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsymfony.com%2Fdoc%2F4.3%2F_images%2Fdocs-pull-request-symfonycloud.png&f=1&nofb=1). 
- [x] Wait until the pull request has been reviewed *and approved* by a teammate
- [ ] After pull request is approved, and you determine it's ready **add the label "Ready to merge"** to the pull request. A bot will *squash and merge* the pull request for you after the label is added. 

- [ ] Merge this branch into `in-app` as it will increase the reliability of it.

2022-06-07 15:27 UTC, levibostian commented on Sources/Tracking/Type/Aliases.swift
> +public typealias Region = Common.Region
This file was added [from this PR](https://github.com/customerio/customerio-ios/pull/166) so I could get Remote Habits to build successfully.

2022-06-07 17:12 UTC, hownowstephen commented on Sources/Tracking/CustomerIOImplementation+ScreenViews.swift
> +        var rootViewController = viewIfLoaded?.window?.rootViewController
any reason you put it here and not at the top of `getActiveRootViewController`?

2022-06-15 19:44 UTC, jasonto commented
Here's the test run: https://app.qase.io/public/report/6866e04c03ad8d8be8fe529601a0adb68fe9b49c

2022-06-15 21:45 UTC, jatinn requested changes
i think the implementation right now may actually discard some events that you may want.
ex. when some products have links to other products
- open product 1 - name: product-page data: product_id = 1
- click to related product
- open product 7 - name: product-page data: product_id = 7

since only the name is used for the comparison the event for viewing product 7 would be lost.

2022-06-15 21:45 UTC, jatinn commented on Sources/Tracking/CustomerIOImplementation.swift
> +        if let previousScreenTrackedName = globalDataStore.lastTrackedScreenName, previousScreenTrackedName == name {
think this could be simplified to `if globalDataStore.lastTrackedScreenName == name {` instead

2022-06-22 21:56 UTC, levibostian commented
PR unblocked as we have chosen to not prevent duplicate events. We will use customer feedback to see what use cases occur and decide on a solution at that time.

2022-06-23 14:35 UTC, merged