ci: test deployments on each pr
customerio/customerio-ios pull request #258
Opened 2023-02-02 21:17 UTC by levibostian

- feat: setup ci to dryrun deployments
- fix branches config to not be blank
- add more output
- simulate squashing and merging PR

Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/blob/develop/docs/dev-notes/GIT-WORKFLOW.md). 
- [ ] [Assign members of your team](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to review the pull request. 
- [ ] Wait for pull request status checks to complete. If there are problems, fix them until you see that [all status checks are passing](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsymfony.com%2Fdoc%2F4.3%2F_images%2Fdocs-pull-request-symfonycloud.png&f=1&nofb=1). 
- [ ] Wait until the pull request has been reviewed *and approved* by a teammate
- [ ] After pull request is approved, and you determine it's ready **add the label "Ready to merge"** to the pull request. A bot will *squash and merge* the pull request for you after the label is added.

2023-02-02 21:18 UTC, levibostian commented
Made this a PR so I can test the CI server (it only runs on PRs). 

This PR not yet ready for review and merging.

2023-02-07 20:11 UTC, levibostian commented
`develop` branch is being removed as part of the strategy to no longer do alpha or beta deployments. This PR is now pointing to `beta` as that's what the old `develop` was.

2023-02-17 11:18 UTC, nunofgs requested changes
Pretty cool. I can see how it could be useful. Left some comments for you.

2023-02-17 11:18 UTC, nunofgs commented on .github/workflows/simulate-merge-pr.yml
> +    types: [opened, edited, synchronize]
This is only relevant when [creating a PR against](https://github.com/customerio/customerio-ios/blob/beta/.github/workflows/deploy-sdk.yml#L5) `main` and `v1` right?

Could we do this?

```suggestion
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - v1
```

2023-02-17 11:18 UTC, nunofgs commented on .github/workflows/test-deployment.yml
> +name: Test deployment
What do you think about renaming this to `test-release`?

No deployment is actually simulated, only versioning and releasing (ie: no assets are uploaded, etc.)

2023-02-17 11:18 UTC, nunofgs commented on .github/workflows/simulate-merge-pr.yml
> +name: Simulate merging a PR
🤔 feels like this file and `test-deployment.yml` could be merged. I don't imagine we'd run the `test-deployment` workflow separately.

If so, I would suggest renaming the file to `simulate-release.yml`.

What do you think?

2023-02-17 11:20 UTC, nunofgs commented
> This question comes from a place that lacks knowledge, so bear with me. Are the yaml files here specifically for this repository or do they represent generic steps that we plan to implement everywhere and so could be part of a CI repo that this might draw from?

@matt-frizzell at the moment it would only apply to this repository. It can definitely be abstracted to a separate actions repo for reusability, but I would recommend trying out the workflow first and making sure that it's useful for the team.

2023-02-17 15:06 UTC, matt-frizzell commented
> > This question comes from a place that lacks knowledge, so bear with me. Are the yaml files here specifically for this repository or do they represent generic steps that we plan to implement everywhere and so could be part of a CI repo that this might draw from?
> 
> @matt-frizzell at the moment it would only apply to this repository. It can definitely be abstracted to a separate actions repo for reusability, but I would recommend trying out the workflow first and making sure that it's useful for the team.

Got it. I had hoped that all work for moving our CI forward would be done generically and drawn from project by project, as we were ready. I think I probably just need a 5-10 catch-up meeting on the current plan so I can understand where we are going from here.

Great steps forward, and very exciting to see!

2023-02-17 15:08 UTC, Shahroz16 commented on .github/workflows/test.yml
>        matrix:
Thank you for this, I didn't know and had to look up what it does 😄 
But from the example, I have seen, it looks like, we don't have to create two jobs, we can use 1 job and not duplicate the steps. You can also provide OS information in `matric`

```
matrix:
        os: [macos-10.14, macos-10.15]
        xcode-version: [11.3, 11.4]
```

2023-02-17 16:08 UTC, nunofgs commented on .github/workflows/simulate-merge-pr.yml
> +    - uses: actions/checkout@v3
🤔 interesting. I haven't found that to be the case. They even list this on [the readme](https://github.com/actions/checkout#checkout-v3): 

> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. 

In any case, I'd prefer not to use older versions unless absolutely necessary. We should measure the perf impact and investigate the underlying issue.

2023-02-17 16:08 UTC, nunofgs commented on .github/workflows/simulate-merge-pr.yml
> +      run: git fetch --depth=1
This can be moved to the actions/checkout above (with `fetchDepth: 0`)

2023-02-17 21:00 UTC, Shahroz16 commented on .github/workflows/simulate-merge-pr.yml
> +    - uses: actions/checkout@v3
[This](https://github.com/actions/checkout/compare/v2.4.2...v3.0.2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L17) is where I got this from. 

But maybe it was just a bad PR change.

2023-09-06 15:16 UTC, levibostian commented
Closing, at least for now. Solution may need a different solution implementation. Will address when task becomes priority for team.

2023-09-06 15:16 UTC, closed without merging