docs: [vision-on-sample-app][11/n] PostInitialization - CIO Intro
customerio/customerio-ios pull request #613
Opened 2024-03-08 13:06 UTC by Ahmed-CIO

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #617
* __->__ #613
* #612
* #611
* #610
* #609
* #608
* #606
* #605
* #604

## Context

This is a PR in a series of PRs to build sample app that runs Identify and Track in VisionPro
The app is built to be an interactive walk through guidance for developers who are integrating Customer.io Swift SDK in their VisioPro apps.
For more context:

- See the project [one pager](https://www.notion.so/custio/Spacial-Identify-and-Tracking-6587d848bbde494095c0585237326ed3?pvs=4)
- See [Linear Issue](https://linear.app/customerio/issue/MBL-115/sample-app-for-visionpro)

## PR Summary
This PR introduces a readonly screen to introduce the developer to CIO as a paltform, what different termenologies used in CIO and the SDK means and how they can be used in a very high level. the usage of the SDK

## Test plan

Make sure the different links in the page navigate to the correct (not yet built) screen or open safari for external URLs

2024-03-08 19:58 UTC, levibostian requested changes
I do like the idea of our sample apps sharing the value of CIO. That's exciting. However, it's also confusing to me because up until now, our sample apps were designed to be QA apps. This is getting into the territory of a showcase app. 

If that is true, I would prefer that this be a team decision to make this sample app have a different purpose then our other sample apps we have built.

2024-03-08 19:58 UTC, levibostian commented on Apps/VisionOS/VisionOS/Assets.xcassets/PostInitialize.imageset/Image@2x.png
My opinion: If this graphic was someone's first exposure to CIO and what it does, this could be overwhelming and a bit complex. 

Is there a way we could "explain it like I'm 5" to the user?

2024-03-10 16:04 UTC, Ahmed-CIO commented on Apps/VisionOS/VisionOS/Assets.xcassets/PostInitialize.imageset/Image@2x.png
This is app is on purpose a customer-first app not a QA app. 
So partially showcase, partially explanation and tutorial-alike.

I am not the best document writer, what you see is best attempt. If you have suggestions please suggest and we can also iterate over it as we go.

Also @glosier will take a look into this content later in this week or the week after and, again, we will iterate as needed.

2024-03-11 02:27 UTC, Ahmed-CIO commented
Apologies for that, gh-stack pushes seems to cause too much noise due to the fact that it pushes the entire stack for every push. These changes will carry on #626

2024-03-11 02:27 UTC, closed without merging