chore: update to lates analytics fork
customerio/customerio-ios pull request #681
Opened 2024-03-29 11:05 UTC by Shahroz16

closes: https://linear.app/customerio/issue/MBL-223/update-segment-fork

The latest fork contains the Apple privacy changes along with other improvements added that can be found here
https://github.com/customerio/cdp-analytics-swift/compare/1.5.5-cio.1...1.5.9+cio.1

2024-03-29 14:38 UTC, mrehan27 commented on Package.swift
> +        .package(name: "Segment", url: "https://github.com/customerio/cdp-analytics-swift.git", .exact("1.5.9+cio.1"))
Shouldn't it be the same as in podspec?

```suggestion
        .package(name: "Segment", url: "https://github.com/customerio/cdp-analytics-swift.git", .exact("1.5.9+cio.2"))
```

2024-04-01 16:54 UTC, levibostian requested changes
I think this PR goes beyond the scope of the ticket. 

The scope of the ticket is to update the segment fork to include the privacy manifest files. Seeing the updates to the .podspec and Package.swift files, those look good to me. 

The rest of the changes go beyond this scope and I don't think are required for the ticket?

2024-04-01 17:11 UTC, Shahroz16 commented
> I think this PR goes beyond the scope of the ticket.
> 
> The scope of the ticket is to update the segment fork to include the privacy manifest files. Seeing the updates to the .podspec and Package.swift files, those look good to me.
> 
> The rest of the changes go beyond this scope and I don't think are required for the ticket?

Correct !!! they were added by mistake, reverting those.

2024-04-01 17:32 UTC, levibostian commented on Tests/DataPipeline/DataPipelineCompatibilityTests.swift
Could you share the reason for this change?

2024-04-01 18:32 UTC, Shahroz16 commented on Tests/DataPipeline/DataPipelineCompatibilityTests.swift
Storage access methods were updated in the segment, which we utilize in our testing and hence had to make those changes accordingly.

2024-04-01 18:38 UTC, levibostian approved these changes

2024-04-01 21:16 UTC, merged