chore: add AutoLayout constraints to make inline messages visible in UIKit app
customerio/customerio-ios pull request #718
Opened 2024-05-17 20:36 UTC by levibostian

Part of: https://linear.app/customerio/issue/MBL-310/create-a-uikit-uiview-that-displays-an-inline-in-app-message-sent-from

This commit implements UIKit AutoLayout constraints to the Inline View and the WebView. Adding these constraints make inline messages visible inside of UIKit apps! The Inline View will start at height 0 and then after the webview content is loaded, it will instantly change the height to display the full in-app message.

Testing:
All testing is done manually in sample apps. AutoLayout constraints change the visuals of Views so viewing how the View looks in an app is required to test.

If you want to test this commit in a sample app build, follow these instructions:
* Open the UIKit app on device.
* Immediately after the app opens, send yourself a test in-app message with element ID "test".
* Wait 10 seconds. In this time, the in-app SDK will fetch the test in-app message and then will display it inline on the screen.

---

**Stack**:
- #718 ⬅
- #717
- #716

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-05-17 20:53 UTC, levibostian commented on Apps/APN-UIKit/APN UIKit/Base.lproj/Main.storyboard
storyboard modified because I added inline Views to the screen. 

I have been talking with Jason on how to QA test this feature. He didn't have specific requirements as far as what screen these Views go, so I added to Dashboard for convenience.

2024-05-17 20:54 UTC, levibostian commented on Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
I added 2 inline Views to the Dashboard screen. So we can test customers can use storyboards or use code to add inline Views to their app.

2024-05-17 20:55 UTC, levibostian commented on Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
Because queue manager stores data in-memory, I had to make it a singleton. All changes in this commit are to make it a singleton.

2024-05-17 20:56 UTC, levibostian commented on Sources/MessagingInApp/Views/InAppMessageView.swift
The main logic of this PR - AutoLayout constraints so messages show up on screen.

2024-05-17 20:56 UTC, levibostian commented on Sources/MessagingInApp/Gist/Gist.swift
>  }
I decided to call `getInlineMessages` directly from `MessageQueueManager` instead of `Gist` to reduce amount of boilerplate code needed.

2024-05-20 14:21 UTC, levibostian commented on Sources/MessagingInApp/Gist/Gist.swift
> -    var messageQueueManager: MessageQueueManager = DIGraphShared.shared.messageQueueManager
Changed because `MessageQueueManager` is a singleton now. Use a property getter to get the shared singleton instance.

2024-05-20 14:22 UTC, levibostian commented on Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
> +// sourcery: InjectSingleton
This class has always been used as a singleton. The whole SDK would use `Gist.messageQueue`. To make the code testable, I switched to instead make the class a singleton in the digraph as we do for all other code in the SDK.

2024-05-20 14:27 UTC, levibostian commented on Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
> -    var interval: Double { get set }
Although I do prefer to use property getter/setters for an API, I found this API to be safer with having the class be a singleton. 

Here is some sample code with what I mean: 

```swift
// If you use a property getter/setter API:
let queueManager: MessageQueueManager = ... get singleton instance 
queueManager.interval = 500
// 🤔 Did we update the shared singleton `inventory` property? Or did we update the `queueManager` local variable, only? 

// if we change to getter/setter functions:
MessageQueueManager.singletonInstance.setInventory(500)
// This is much more clear that we are editing the singleton, not a locally scoped instance. 
```

2024-05-20 14:30 UTC, levibostian commented on Sources/MessagingInApp/Views/InAppMessageView.swift
Added autolayout code to the View so we can now display the web content in the View.

2024-05-20 19:31 UTC, levibostian commented on Apps/APN-UIKit/APN UIKit/View/DashboardViewController.swift
> +            newInlineViewUsingUIAsCode.centerXAnchor.constraint(equalTo: randomEventButton.centerXAnchor).isActive = true
During QA testing, I noticed what might be a bug with this code. 

steps: 
* Send yourself 2 inline test messages so you have both inline Views showing messages in the app. 
* Scroll down the screen. When you put your finger in the middle of 1 of the inline Views and scroll your finger, the screen moves with your finger. But for the other inline View (this one I added via code), the screen does not move with your finger. 

I think that this is a bug with the AutoLayout code here which means it's a bug in the sample app and not with the SDK.

2024-05-23 18:37 UTC, Ahmed-Ali requested changes
This is a very UI heavy code. A small video showing how it looks like and what have been tested would make the code review much easier.

2024-05-28 18:52 UTC, levibostian commented
Video added to description of PR.

2024-06-03 19:43 UTC, Ahmed-Ali approved these changes

2024-06-04 20:05 UTC, merged