chore: refactor in-app queue classes
customerio/customerio-ios pull request #802
Opened 2024-09-02 17:39 UTC by mrehan27

part of [MBL-480](https://linear.app/customerio/issue/MBL-480/update-in-app-messaging-module-using-state-management-in-ios)

### Changes

- Updated `Gist`, `MessageManager`, and `QueueManager` classes to use the newly added state and manager
- Removed shared Gist instance and moved `Gist`, `MessageManager`, and `QueueManager` to `DiGraph`

2024-09-04 07:25 UTC, Shahroz16 requested changes
From the looks of it seems like we are not reliant on event listener added by the customer and even the journey actions won't be triggered if that's not provided, which shouldn't be the way

2024-09-04 09:56 UTC, Shahroz16 reviewed
Discussed on call, callbacks should work, now its down to suggestions only

2024-09-04 09:56 UTC, Shahroz16 commented on Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
maybe this can be removed as its usage is quite similar to Gist class?

2024-09-04 09:56 UTC, Shahroz16 commented on Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
> +            threadUtil.runMainAfterDelay(deadline: .now() + 1) {
now that we are waiting for initializing task to finish, we might not need to delay?

2024-09-04 11:20 UTC, mrehan27 commented on Sources/MessagingInApp/Gist/Gist.swift
> +    func setEventListener(_ eventListener: InAppEventListener?) {
Resolved on call

2024-09-04 11:21 UTC, mrehan27 commented on Sources/MessagingInApp/Gist/Managers/MessageQueueManager.swift
Yup, merged into one

2024-09-05 06:41 UTC, mrehan27 commented on Sources/MessagingInApp/Gist/Managers/MessageManager.swift
> +        }
Discussed on call, we'll merge this for now and think later more on this later

2024-09-05 06:41 UTC, mrehan27 commented on Sources/MessagingInApp/Gist/Managers/MessageManager.swift
> +                guard let _ = self else { return }
Discussed on call, will be merging this as it looks okay

2024-09-05 06:42 UTC, merged